/**
 * Podcast episodes — a two-host dialogue show rendered to a single MP3.
 *
 * The script can be imported by the user (with [HostName] speaker tags, or
 * plain paragraphs that get alternated between the hosts) or generated by the
 * LLM from a topic. Each host plugs in their own voice AI: any TTS adapter
 * the platform supports, typically a Mistral Voxtral preset voice or an
 * ElevenLabs voice — including cloned voices, since a clone is addressed by
 * its ordinary ElevenLabs voice_id.
 */
import { getPool } from '../db.js';
import { config } from '../config.js';
import { getTtsAdapter } from '../adapters/tts/openai.js';
import { getStorageAdapter } from '../lib/storage/index.js';
import { llmComplete } from '../adapters/llm/index.js';
import { withRetry } from '../utils/retry.js';
import { parseDialogueLines, estimateMp3Duration } from './ttsService.js';
import { execFile } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import os from 'os';
import path from 'path';

const execFileAsync = promisify(execFile);

export const SUPPORTED_VOICE_PROVIDERS = [
  'mistral', 'elevenlabs', 'openai', 'google', 'gemini_tts', 'narakeet',
] as const;

export interface PodcastHost {
  name: string;
  provider: string;
  voice_id: string;
  /** Bring-your-own key — used for rendering, never persisted. */
  api_key?: string;
}

export interface PodcastEpisode {
  id: string;
  station_id: string;
  title: string;
  source: 'imported' | 'generated';
  topic: string | null;
  script_text: string;
  hosts: Array<Omit<PodcastHost, 'api_key'>>;
  status: 'pending' | 'generating_script' | 'rendering' | 'ready' | 'failed';
  error_message: string | null;
  audio_url: string | null;
  audio_duration_sec: number | null;
  created_at: Date;
  updated_at: Date;
}

export function validateHosts(hosts: unknown): string | null {
  if (!Array.isArray(hosts) || hosts.length !== 2) {
    return 'hosts must be an array of exactly 2 hosts';
  }
  for (const h of hosts as PodcastHost[]) {
    if (!h?.name?.trim()) return 'each host needs a name';
    if (!SUPPORTED_VOICE_PROVIDERS.includes(h?.provider as never)) {
      return `host "${h?.name}": provider must be one of ${SUPPORTED_VOICE_PROVIDERS.join(', ')}`;
    }
    if (!h?.voice_id?.trim()) return `host "${h.name}" needs a voice_id`;
  }
  const [a, b] = hosts as PodcastHost[];
  if (a.name.trim().toLowerCase() === b.name.trim().toLowerCase()) {
    return 'hosts must have distinct names';
  }
  return null;
}

function defaultApiKeyFor(provider: string): string {
  switch (provider) {
    case 'elevenlabs': return config.tts.elevenlabsApiKey;
    case 'mistral':    return config.tts.mistralApiKey;
    case 'openai':     return config.tts.openaiApiKey;
    case 'google':     return config.tts.googleApiKey;
    case 'gemini_tts': return config.tts.geminiApiKey;
    case 'narakeet':   return config.tts.narakeetApiKey;
    default:           return '';
  }
}

/**
 * Ensure the script is [HostName]-tagged dialogue. Plain text (no tags) is
 * alternated paragraph-by-paragraph between the two hosts so users can paste
 * any script and still get the two-presenter format.
 */
export function normalizeScript(scriptText: string, hosts: PodcastHost[]): string {
  const hasTags = /\[[^\]]+\]/.test(scriptText);
  if (hasTags) return scriptText.trim();

  const paragraphs = scriptText
    .split(/\n\s*\n|\n/)
    .map(p => p.trim())
    .filter(Boolean);
  return paragraphs
    .map((p, i) => `[${hosts[i % 2].name}] ${p}`)
    .join('\n');
}

export async function createEpisode(input: {
  station_id: string;
  title: string;
  hosts: PodcastHost[];
  script_text?: string;
  topic?: string;
  created_by?: string;
}): Promise<PodcastEpisode> {
  const source = input.script_text?.trim() ? 'imported' : 'generated';
  const persistedHosts = input.hosts.map(({ api_key: _key, ...rest }) => rest);
  const { rows } = await getPool().query<PodcastEpisode>(
    `INSERT INTO dj_podcast_episodes
       (station_id, title, source, topic, script_text, hosts, status, created_by)
     VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7)
     RETURNING *`,
    [
      input.station_id,
      input.title,
      source,
      input.topic ?? null,
      input.script_text?.trim() ?? '',
      JSON.stringify(persistedHosts),
      input.created_by ?? null,
    ],
  );
  return rows[0];
}

export async function listEpisodes(stationId: string): Promise<PodcastEpisode[]> {
  const { rows } = await getPool().query<PodcastEpisode>(
    `SELECT * FROM dj_podcast_episodes WHERE station_id = $1 ORDER BY created_at DESC`,
    [stationId],
  );
  return rows;
}

export async function getEpisode(id: string): Promise<PodcastEpisode | null> {
  const { rows } = await getPool().query<PodcastEpisode>(
    `SELECT * FROM dj_podcast_episodes WHERE id = $1`,
    [id],
  );
  return rows[0] ?? null;
}

export async function deleteEpisode(id: string): Promise<boolean> {
  const { rowCount } = await getPool().query(
    `DELETE FROM dj_podcast_episodes WHERE id = $1`,
    [id],
  );
  return (rowCount ?? 0) > 0;
}

async function setStatus(id: string, status: string, patch: Record<string, unknown> = {}): Promise<void> {
  const fields = ['status = $2', 'updated_at = NOW()'];
  const values: unknown[] = [id, status];
  let i = 3;
  for (const [key, value] of Object.entries(patch)) {
    fields.push(`${key} = $${i++}`);
    values.push(value);
  }
  await getPool().query(
    `UPDATE dj_podcast_episodes SET ${fields.join(', ')} WHERE id = $1`,
    values,
  );
}

async function generatePodcastScript(episode: PodcastEpisode, hosts: PodcastHost[]): Promise<string> {
  const [a, b] = hosts;
  const llmResult = await llmComplete(
    [
      {
        role: 'system',
        content:
          'You write natural, engaging two-host podcast dialogue. ' +
          `The hosts are "${a.name}" and "${b.name}". ` +
          `Format every line as [${a.name}] or [${b.name}] followed by what that host says. ` +
          'Alternate naturally: banter, questions, reactions. No stage directions, no markdown — only tagged dialogue lines.',
      },
      {
        role: 'user',
        content:
          `Write a podcast episode titled "${episode.title}" about: ${episode.topic}. ` +
          'Open with both hosts introducing the show, cover the topic conversationally, and close with a sign-off. ' +
          'Aim for roughly 20-30 dialogue exchanges.',
      },
    ],
    { temperature: 0.9 },
  );
  return llmResult.text.trim();
}

/**
 * Render an episode: resolve the script, TTS every dialogue line with the
 * speaking host's own provider/voice, stitch the clips into one MP3, store
 * it, and mark the episode ready. Designed to run fire-and-forget.
 */
export async function renderEpisode(episodeId: string, hosts: PodcastHost[]): Promise<void> {
  const episode = await getEpisode(episodeId);
  if (!episode) return;

  try {
    let script = episode.script_text;
    if (!script.trim()) {
      await setStatus(episodeId, 'generating_script');
      script = await generatePodcastScript(episode, hosts);
    }
    script = normalizeScript(script, hosts);
    await setStatus(episodeId, 'rendering', { script_text: script });

    const lines = parseDialogueLines(script);
    if (lines.length === 0) throw new Error('Script produced no dialogue lines');

    const hostByName = new Map(hosts.map(h => [h.name.trim().toLowerCase(), h]));
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'podcast-'));
    try {
      const clipPaths: string[] = [];
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const host = hostByName.get(line.speaker.trim().toLowerCase()) ?? hosts[0];
        const adapter = getTtsAdapter({
          provider: host.provider,
          apiKey: host.api_key || defaultApiKeyFor(host.provider),
          model: host.provider === 'elevenlabs' ? config.tts.elevenlabsModel : undefined,
        });
        const result = await withRetry(
          () => adapter.generate({ voice_id: host.voice_id, text: line.text }),
          { label: `podcast/line-${i}` },
        );
        const clipPath = path.join(tmpDir, `clip-${String(i).padStart(4, '0')}.mp3`);
        fs.writeFileSync(clipPath, result.audio_data);
        clipPaths.push(clipPath);

        // Direct insert: dj_usage_log.script_id FKs dj_scripts, which podcast
        // episodes are not — log with a null script_id instead of logTtsUsage.
        getPool().query(
          `INSERT INTO dj_usage_log
             (station_id, usage_type, provider, character_count, metadata)
           VALUES ($1, 'tts', $2, $3, $4)`,
          [
            episode.station_id,
            host.provider,
            line.text.length,
            JSON.stringify({ kind: 'podcast', episode_id: episodeId, host: host.name }),
          ],
        ).catch(() => undefined);
      }

      // 350ms silence between exchanges for a podcast-like pace
      const silencePath = path.join(tmpDir, 'silence.mp3');
      await execFileAsync('ffmpeg', [
        '-f', 'lavfi', '-i', 'anullsrc=r=44100:cl=mono',
        '-t', '0.35', '-c:a', 'libmp3lame', '-b:a', '128k',
        '-y', silencePath,
      ], { timeout: 10000 });

      const concatListPath = path.join(tmpDir, 'concat.txt');
      const entries: string[] = [];
      for (let i = 0; i < clipPaths.length; i++) {
        entries.push(`file '${clipPaths[i]}'`);
        if (i < clipPaths.length - 1) entries.push(`file '${silencePath}'`);
      }
      fs.writeFileSync(concatListPath, entries.join('\n'));

      // Re-encode to a uniform MP3 (clips may come from different providers
      // with different sample rates, so stream-copy concat is not safe).
      const finalPath = path.join(tmpDir, 'episode.mp3');
      await execFileAsync('ffmpeg', [
        '-f', 'concat', '-safe', '0', '-i', concatListPath,
        '-c:a', 'libmp3lame', '-b:a', '128k', '-ar', '44100', '-ac', '1',
        '-y', finalPath,
      ], { timeout: 120000 });

      const audio = fs.readFileSync(finalPath);
      let duration: number | null = null;
      try {
        const { stdout } = await execFileAsync('ffprobe', [
          '-v', 'quiet', '-print_format', 'json', '-show_format', finalPath,
        ], { timeout: 5000 });
        duration = parseFloat(JSON.parse(stdout).format.duration);
      } catch {
        duration = estimateMp3Duration(audio);
      }

      const storagePath = `podcasts/${episodeId}.mp3`;
      const storage = getStorageAdapter();
      await storage.write(storagePath, audio);
      const publicUrl = storage.getPublicUrl(storagePath);
      const audioUrl = publicUrl.startsWith('http')
        ? `${publicUrl}?v=${Date.now()}`
        : `/api/v1/dj/audio/${storagePath}`;

      await setStatus(episodeId, 'ready', {
        audio_url: audioUrl,
        audio_duration_sec: duration,
        error_message: null,
      });
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  } catch (err) {
    await setStatus(episodeId, 'failed', {
      error_message: err instanceof Error ? err.message : String(err),
    }).catch(() => undefined);
  }
}
